### ISSUE TITLE
In version 2: Could not create backup of db L5.0 

### ISSUE THREAD

**Issue by nam-co** [spatie/laravel-backup#37] opened 2015-05-19 21:47 UTC
Hi freekmurze, sorry to bother you but Im getting this same errors in the local and digital ocean servers with the S3 and local settings, can you please tell me what can be wrong? mysqldump is install

appreciate any help, thanks and cool package can it be automatic with the new options in L5.1?

1. php artisan backup:run
Start backing up
Determining which files should be backed up...
[ErrorException]                         
Invalid argument supplied for foreach()  

2. php artisan backup:run --only-db
Start backing up                
  [Exception]                    
  Could not create backup of db

**Comment by freekmurze** [comment] 2015-05-20 05:37
Things you can check:
- does the destination directory exists? Is it writable. When backing up to S3, is the path in the bucket writable?
- are the files specified in source.files.include and source.files.exclude correct?

If you can't find any issues, run the command with the -vvv flag to get more detail on the exception. 

Though I haven't tested it out the package should work perfectly with L5.1 As soon as that version is available, I'll check it to make sure.

**Comment by mfsi-praveenm** [comment] 2015-05-26 09:27
can you cite an example for paths because i am getting the same issue.

**Comment by freekmurze** [comment] 2015-05-26 11:25
There are paths configured in the config file by default

**Comment by mfsi-praveenm** [comment] 2015-05-26 11:27
i have tried in my local machine with path mentioned,I am not sure where the 'backups' folder should reside.

**Comment by nam-co** [comment] 2015-05-26 15:02
Hi Freekmurze, I set up to S3 in a new different app using server pilot and run: php5.6-sp artisan backup:run
the response was: 
Start backing up
[Exception]                    
Could not create backup of db  
Exception trace:
 () at /srv/users/serverpilot/apps/appname/vendor/spatie/laravel-backup/src/BackupHandlers/Database/DatabaseBackupHandler.php:44
 Spatie\Backup\BackupHandlers\Database\DatabaseBackupHandler->getDumpedDatabase() at /srv/users/serverpilot/apps/appname/vendor/spatie/laravel-backup/src/BackupHandlers/Database/DatabaseBackupHandler.php:57
 Spatie\Backup\BackupHandlers\Database\DatabaseBackupHandler->getFilesToBeBackedUp() at /srv/users/serverpilot/apps/appname/vendor/spatie/laravel-backup/src/Commands/BackupCommand.php:63
 Spatie\Backup\Commands\BackupCommand->getAllFilesToBeBackedUp() at /srv/users/serverpilot/apps/appname/vendor/spatie/laravel-backup/src/Commands/BackupCommand.php:33
 Spatie\Backup\Commands\BackupCommand->fire() at n/a:n/a
 call_user_func_array() at /srv/users/serverpilot/apps/appname/bootstrap/cache/compiled.php:924
 Illuminate\Container\Container->call() at /srv/users/serverpilot/apps/appname/vendor/laravel/framework/src/Illuminate/Console/Command.php:149
 Illuminate\Console\Command->execute() at /srv/users/serverpilot/apps/appname/vendor/symfony/console/Command/Command.php:259
 Symfony\Component\Console\Command\Command->run() at /srv/users/serverpilot/apps/appname/vendor/laravel/framework/src/Illuminate/Console/Command.php:135
 Illuminate\Console\Command->run() at /srv/users/serverpilot/apps/appname/vendor/symfony/console/Application.php:878
 Symfony\Component\Console\Application->doRunCommand() at /srv/users/serverpilot/apps/appname/vendor/symfony/console/Application.php:195
 Symfony\Component\Console\Application->doRun() at /srv/users/serverpilot/apps/appname/vendor/symfony/console/Application.php:126
 Symfony\Component\Console\Application->run() at /srv/users/serverpilot/apps/appname/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:94
 Illuminate\Foundation\Console\Kernel->handle() at /srv/users/serverpilot/apps/appname/artisan:36


I also tried in both 5.1 and 5.0 so is another problem
Also how do we make sure the S3 destination is it writable? sorry about all this, but your package seems the best and I will really like to use it

**Comment by freekmurze** [comment] 2015-05-26 15:31
You could try putting a file on S3 with the [configured Filesystem](http://laravel.com/docs/master/filesystem)

```php
Storage::disk('nameOfYourConfiguredFilesystem')->put('file.txt', 'Contents');
```

**Comment by nam-co** [comment] 2015-05-26 16:37
Hi Freek, thanks for your response, but I don't think the problem is in S3, because when I choose local it doesn't work, could the problem be the app is using serverpilot?

I try the Storage to S3 and it didn't worked, I change the key and it work, tried again the backup and still same problem (Could not create backup of db)

Thanks

**Comment by nam-co** [comment] 2015-05-26 16:55
ok, is not server pilot because I test in my local server using mamp and same error with both (local and S3)

**Comment by freekmurze** [comment] 2015-06-03 16:16
Are you sure mysqldump is installed on your system? Could you try running it manually to see if it creates a dump of your db?

**Comment by sethphillips** [comment] 2015-06-30 15:22
I was facing this same issue, however only on a windows deployment.  In development on my mac it ran fine.  I had to set the default path for mysqldump in the config to "C:/Program Files/MySQL/MySQL Server 5.6/bin/" and then it worked.

**Comment by sethphillips** [comment] 2015-07-10 19:48
Ive just ran into this on another windows server and the above solution does not work for it.  I've verified that mysqldump does work on the system

**Comment by ilkermutlu** [comment] 2015-07-13 07:28
I recently had the same issue. (OS X, MAMP)

It turned out that my mysqldump path was incorrect. In my case a full path to the binary was provided. I replaced it with the path to the directory.

**Comment by RSNKumar** [comment] 2015-08-03 04:54
I too have same issue. Could any one help me?

**Comment by freekmurze** [comment] 2015-09-05 21:56
@RSNKumar could you try @ilkermutlu 's solution?

**Comment by anhtuank7c** [comment] 2015-09-20 05:00
Resolution for error could not backup db.
You must setup environment path to mysql.
I'm use windows 7, and here my path to mysql: C:\Program Files\MySQL\MySQL Server 5.6\bin
I do copy this path and paste to System path environment,then click ok.
![](http://i.imgur.com/varqtAX.png)
Open new Command Line then execute: php artisan backup:run
It's work like a boss.
![](http://i.imgur.com/L5AkJf7.png)

**Comment by freekmurze** [comment] 2015-09-21 08:53
@anhtuank7c thanks! :+1:

**Comment by lucidlemon** [comment] 2015-09-30 19:46
i can't get it running either.

```
php artisan backup:run --only-db -vvv
Start backing up


                                 
  [Exception]                    
  Could not create backup of db  
                                 


Exception trace:
 () at /var/www/staging/webshop/vendor/spatie/laravel-backup/src/BackupHandlers/Database/DatabaseBackupHandler.php:47
 Spatie\Backup\BackupHandlers\Database\DatabaseBackupHandler->getDumpedDatabase() at /var/www/staging/webshop/vendor/spatie/laravel-backup/src/BackupHandlers/Database/DatabaseBackupHandler.php:60
 Spatie\Backup\BackupHandlers\Database\DatabaseBackupHandler->getFilesToBeBackedUp() at /var/www/staging/webshop/vendor/spatie/laravel-backup/src/Commands/BackupCommand.php:67
 Spatie\Backup\Commands\BackupCommand->getAllFilesToBeBackedUp() at /var/www/staging/webshop/vendor/spatie/laravel-backup/src/Commands/BackupCommand.php:33
 Spatie\Backup\Commands\BackupCommand->fire() at n/a:n/a
 call_user_func_array() at /var/www/staging/webshop/vendor/laravel/framework/src/Illuminate/Container/Container.php:502
 Illuminate\Container\Container->call() at /var/www/staging/webshop/vendor/laravel/framework/src/Illuminate/Console/Command.php:150
 Illuminate\Console\Command->execute() at /var/www/staging/webshop/vendor/symfony/console/Command/Command.php:259
 Symfony\Component\Console\Command\Command->run() at /var/www/staging/webshop/vendor/laravel/framework/src/Illuminate/Console/Command.php:136
 Illuminate\Console\Command->run() at /var/www/staging/webshop/vendor/symfony/console/Application.php:878
 Symfony\Component\Console\Application->doRunCommand() at /var/www/staging/webshop/vendor/symfony/console/Application.php:195
 Symfony\Component\Console\Application->doRun() at /var/www/staging/webshop/vendor/symfony/console/Application.php:126
 Symfony\Component\Console\Application->run() at /var/www/staging/webshop/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:100
 Illuminate\Foundation\Console\Kernel->handle() at /var/www/staging/webshop/artisan:36
```

Standard Filesystem settings, directory backups created, Laravel 5.1, also added it with ::class etc.. everything like it should.
I can also create a mysqldump as the www-data user myself from the command line, just not with this plugin.

Any ideas?

**Comment by REBELinBLUE** [comment] 2015-10-07 16:12
Yep, exactly the same issue with Laravel 5.1, Debian, Standard config, created the backup directory, mysqldump is in the default location but I added it to the config as well just in case

**Comment by Sarnodeep** [comment] 2015-10-28 08:29
anhtuank7c thanks :+1:

**Comment by adrinavarro** [comment] 2015-11-03 00:26
I second this because I'm seeing this as well. Had it happen on a first setup, then after migrating the server it's happening again, and it takes hours of debugging because the error message and trace isn't really clear.

Now, back to figuring it out…

**Comment by adrinavarro** [comment] 2015-11-03 00:38
Ooh. Seems the culprit is hhvm. Should not get the uri for stream_get_meta_data. A workaround should be feasible.

https://github.com/facebook/hhvm/issues/2336

**Comment by jpscharf** [comment] 2015-11-09 17:04
I am having the same problem, and I am not using hhvm:
```
Start backing up



  [Exception]
  Could not create backup of db



Exception trace:
 () at /home/forge/dev.essentialoils.org/vendor/spatie/laravel-backup/src/BackupHandlers/Database/DatabaseBackupHandler.php:46
 Spatie\Backup\BackupHandlers\Database\DatabaseBackupHandler->getDumpedDatabase() at /home/forge/dev.essentialoils.org/vendor/spatie/laravel-backup/src/BackupHandlers/Database/DatabaseBackupHandler.php:59
 Spatie\Backup\BackupHandlers\Database\DatabaseBackupHandler->getFilesToBeBackedUp() at /home/forge/dev.essentialoils.org/vendor/spatie/laravel-backup/src/Commands/BackupCommand.php:254
 Spatie\Backup\Commands\BackupCommand->getDatabaseDump() at /home/forge/dev.essentialoils.org/vendor/spatie/laravel-backup/src/Commands/BackupCommand.php:70
 Spatie\Backup\Commands\BackupCommand->getAllFilesToBeBackedUp() at /home/forge/dev.essentialoils.org/vendor/spatie/laravel-backup/src/Commands/BackupCommand.php:35
 Spatie\Backup\Commands\BackupCommand->fire() at n/a:n/a
 call_user_func_array() at /home/forge/dev.essentialoils.org/vendor/laravel/framework/src/Illuminate/Container/Container.php:503
 Illuminate\Container\Container->call() at /home/forge/dev.essentialoils.org/vendor/laravel/framework/src/Illuminate/Console/Command.php:150
 Illuminate\Console\Command->execute() at /home/forge/dev.essentialoils.org/vendor/symfony/console/Command/Command.php:256
 Symfony\Component\Console\Command\Command->run() at /home/forge/dev.essentialoils.org/vendor/laravel/framework/src/Illuminate/Console/Command.php:136
 Illuminate\Console\Command->run() at /home/forge/dev.essentialoils.org/vendor/symfony/console/Application.php:838
 Symfony\Component\Console\Application->doRunCommand() at /home/forge/dev.essentialoils.org/vendor/symfony/console/Application.php:189
 Symfony\Component\Console\Application->doRun() at /home/forge/dev.essentialoils.org/vendor/symfony/console/Application.php:120
 Symfony\Component\Console\Application->run() at /home/forge/dev.essentialoils.org/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:107
 Illuminate\Foundation\Console\Kernel->handle() at /home/forge/dev.essentialoils.org/artisan:36
```

**Comment by ekstro** [comment] 2015-12-03 10:17
Same problem.

```
  [Exception]
  Could not create backup of db



Exception trace:
 () at /Users/ekstro/Documents/Websites/radioin/vendor/spatie/laravel-backup/src/BackupHandlers/Database/DatabaseBackupHandler.php:46
 Spatie\Backup\BackupHandlers\Database\DatabaseBackupHandler->getDumpedDatabase() at /Users/ekstro/Documents/Websites/radioin/vendor/spatie/laravel-backup/src/BackupHandlers/Database/DatabaseBackupHandler.php:59
 Spatie\Backup\BackupHandlers\Database\DatabaseBackupHandler->getFilesToBeBackedUp() at /Users/ekstro/Documents/Websites/radioin/vendor/spatie/laravel-backup/src/Commands/BackupCommand.php:265
 Spatie\Backup\Commands\BackupCommand->getDatabaseDump() at /Users/ekstro/Documents/Websites/radioin/vendor/spatie/laravel-backup/src/Commands/BackupCommand.php:81
 Spatie\Backup\Commands\BackupCommand->getAllFilesToBeBackedUp() at /Users/ekstro/Documents/Websites/radioin/vendor/spatie/laravel-backup/src/Commands/BackupCommand.php:44
 Spatie\Backup\Commands\BackupCommand->fire() at n/a:n/a
 call_user_func_array() at /Users/ekstro/Documents/Websites/radioin/vendor/laravel/framework/src/Illuminate/Container/Container.php:503
 Illuminate\Container\Container->call() at /Users/ekstro/Documents/Websites/radioin/vendor/laravel/framework/src/Illuminate/Console/Command.php:150
 Illuminate\Console\Command->execute() at /Users/ekstro/Documents/Websites/radioin/vendor/symfony/console/Command/Command.php:256
 Symfony\Component\Console\Command\Command->run() at /Users/ekstro/Documents/Websites/radioin/vendor/laravel/framework/src/Illuminate/Console/Command.php:136
 Illuminate\Console\Command->run() at /Users/ekstro/Documents/Websites/radioin/vendor/symfony/console/Application.php:838
 Symfony\Component\Console\Application->doRunCommand() at /Users/ekstro/Documents/Websites/radioin/vendor/symfony/console/Application.php:189
 Symfony\Component\Console\Application->doRun() at /Users/ekstro/Documents/Websites/radioin/vendor/symfony/console/Application.php:120
 Symfony\Component\Console\Application->run() at /Users/ekstro/Documents/Websites/radioin/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:107
 Illuminate\Foundation\Console\Kernel->handle() at /Users/ekstro/Documents/Websites/radioin/artisan:36
```

**Comment by ekstro** [comment] 2015-12-03 10:47
In my case problem was with temporary config file for mysqldump (one generated with tmpfile() in dump method). When you defined host in Laravel config file as eg. "localhost:8889" (with port) this causing the problem.

```
[client]
user = 'root'
password = 'lopawq2012'
host = 'localhost:8889'
port = '3306'
```

This is working for me:

```
[client]
user = 'root'
password = 'lopawq2012'
host = 'localhost'
port = '8889'
```

**Comment by starship11** [comment] 2016-01-14 07:21
is there any way to call the same artisan command from laravel controller?? when called from controller it gives error "could not backup db" :(

**Comment by freekmurze** [comment] 2016-01-15 20:51
@starship11 If you configured the package correctly you can use this code in your project to perform a backup.
```php
\Artisan::call('backup:run');
```

**Comment by DerJacques** [comment] 2016-01-22 09:23
I received the same error message, but in my case it was 100% my own fault.
Just for the record, I'm using MySQL and AWS S3.

* If you are running Laravel in a VM, make sure to run the command from within the VM (or wherever mysqldump is installed).
* Inserting `dd($success)` in `/vendor/spatie/laravel-backup/src/BackupHandlers/Database/DatabaseBackupHandler.php` on `line 44` might provide you with a more detailed error message.

Not sure if my issue was related to the ones you folks are experiencing, but maybe this helps.

**Comment by freekmurze** [comment] 2016-01-22 09:25
@DerJacques  Thanks for taking the time to post your solution :+1:

**Comment by anandatheerthan** [comment] 2016-01-25 16:54
Start backing up
"mysqldump: Got error: 1045: "Access denied for user 'root'@'localhost' (using password: NO)" when trying to connect\n"

Why is it using root user and not the user specified in config file.

**Comment by freekmurze** [comment] 2016-01-25 17:49
Did you save your credentials in the config file?

**Comment by anandatheerthan** [comment] 2016-01-25 18:19
<?php

return [

    /*
    |--------------------------------------------------------------------------
    | PDO Fetch Style
    |--------------------------------------------------------------------------
    |
    | By default, database results will be returned as instances of the PHP
    | stdClass object; however, you may desire to retrieve records in an
    | array format for simplicity. Here you can tweak the fetch style.
    |
    */

    'fetch' => PDO::FETCH_CLASS,

    /*
    |--------------------------------------------------------------------------
    | Default Database Connection Name
    |--------------------------------------------------------------------------
    |
    | Here you may specify which of the database connections below you wish
    | to use as your default connection for all database work. Of course
    | you may use many connections at once using the Database library.
    |
    */

    'default' =>  'mysql',

    /*
    |--------------------------------------------------------------------------
    | Database Connections
    |--------------------------------------------------------------------------
    |
    | Here are each of the database connections setup for your application.
    | Of course, examples of configuring each database platform that is
    | supported by Laravel is shown below to make development simple.
    |
    |
    | All database work in Laravel is done through the PHP PDO facilities
    | so make sure you have the driver for your particular database of
    | choice installed on your machine before you begin development.
    |
    */

    'connections' => [

        'sqlite' => [
            'driver'   => 'sqlite',
            'database' => storage_path('database.sqlite'),
            'prefix'   => '',
        ],

        'mysql' => [
            'driver'    => 'mysql',
            'host'      => 'localhost',
            'database'  => 'thejanso_anand',
            'username'  => 'thejanso_anand',
            'password'  => 'wewewew',
            'charset'   => 'utf8',
            'collation' => 'utf8_unicode_ci',
            'prefix'    => '',
            'strict'    => false,
        ],

        'pgsql' => [
            'driver'   => 'pgsql',
            'host'     => env('DB_HOST', 'localhost'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'charset'  => 'utf8',
            'prefix'   => '',
            'schema'   => 'public',
        ],

        'sqlsrv' => [
            'driver'   => 'sqlsrv',
            'host'     => env('DB_HOST', 'localhost'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'charset'  => 'utf8',
            'prefix'   => '',
        ],

    ],

    /*
    |--------------------------------------------------------------------------
    | Migration Repository Table
    |--------------------------------------------------------------------------
    |
    | This table keeps track of all the migrations that have already run for
    | your application. Using this information, we can determine which of
    | the migrations on disk haven't actually been run in the database.
    |
    */

    'migrations' => 'migrations',

    /*
    |--------------------------------------------------------------------------
    | Redis Databases
    |--------------------------------------------------------------------------
    |
    | Redis is an open source, fast, and advanced key-value store that also
    | provides a richer set of commands than a typical key-value systems
    | such as APC or Memcached. Laravel makes it easy to dig right in.
    |
    */

    'redis' => [

        'cluster' => false,

        'default' => [
            'host'     => '127.0.0.1',
            'port'     => 6379,
            'database' => 0,
        ],

    ],

];

**Comment by anandatheerthan** [comment] 2016-01-25 18:30
do I need to make any changes.


Regards,
Anand

**Comment by DerJacques** [comment] 2016-01-25 18:34
Do you have any other database config-files?
You might want to check if there's a different config in a folder called `config/production` or `config/local`.

Make sure that your Laravel database connection works fine otherwise. The error you experience does not necessarily seem to be related to this package.

**Comment by anandatheerthan** [comment] 2016-01-25 18:38
Hi,
I do not have multiple config files. I am using default installation only
and am able to run the site which uses this database. The database had
different user than root. Why root user is being picked and from where.


Regards,
Anand

**Comment by anandatheerthan** [comment] 2016-01-26 04:26
I am using hhvm, guess that is causing the issue. Any workaround or solution available yet.

**Comment by anandatheerthan** [comment] 2016-01-26 04:32
Fixed by changing Line 50 as highlighted in MySQLDatabase.php

![capture](https://cloud.githubusercontent.com/assets/7847452/12572539/e811ca8a-c441-11e5-8767-5f07bacf4c42.PNG)

**Comment by devLopez** [comment] 2016-01-28 12:57
Hi guys

I'm having a problem with the backup of database. When I run the artisan command on CLI, the database backup works perfectly, but I need run the backup command inside a Controller, and then, I receive error "Could not create backup of db".

How I can proceed?

God Bless

**Comment by freekmurze** [comment] 2016-01-30 11:04
@devLopez If it can run on the cli, it should work in the controller as well. Does your application is alle to connect to the database inside the controller? Could you show the code that you're using to run the backup command?

**Comment by devLopez** [comment] 2016-02-02 11:24
@freekmurze, down, I took a print screen of my source code. I've created a controller only for manage my backup actions.

God Bless

![backup-artisan-error](https://cloud.githubusercontent.com/assets/5889460/12747985/8092c88a-c98e-11e5-9623-654f8340e24a.jpg)

**Comment by freekmurze** [comment] 2016-02-02 11:28
Seems good. Are you sure it works on the cli? From a package standpoint there's no difference in calling it from cli or calling the command from your controller. I the problem is caused by something specific to your setup.

**Comment by devLopez** [comment] 2016-02-02 11:47
@freekmurze 

Works very well, take a look

![error-laravel-db](https://cloud.githubusercontent.com/assets/5889460/12748526/fbc8c5ec-c991-11e5-9775-81f2fd543ede.jpg)

**Comment by freekmurze** [comment] 2016-02-02 12:04
Is the process that handles your web requests allowed to execute external programs like `mysqldump`?

**Comment by devLopez** [comment] 2016-02-02 12:07
Oh men, you got me!!!

I don't know, how I can see it?

**Comment by freekmurze** [comment] 2016-02-02 12:20
I'm not familiar with running php on windows.

**Comment by devLopez** [comment] 2016-02-02 12:32
I'm thinking, backups generated manually can be a bad thing.
The user can forget it.
I'll do it working with cron jobs, is more secure.

God Bless you men, thanks

**Comment by jpscharf** [comment] 2016-02-16 21:22
Backup will fail if the port is included/inlined with the host, e.g `DB_HOST=localhost:3306`.
- The solution for my issue was to add `DB_PORT` to `.env` and `'port' => env('DB_PORT', 3306)` to config/database.php

**Comment by freekmurze** [comment] 2016-03-09 13:09
I'm going to close this for now. If you have any more troubles with v2 of this package, try upgrading to v3

**Closed by freekmurze** 2016-03-09 13:09 UTC

**Comment by devLopez** [comment] 2016-03-09 13:54
Ok men

**Comment by nam-co** [comment] 2016-03-09 17:12
thanks for v3
