### ISSUE TITLE
Error in backup:run

### ISSUE THREAD

**Issue by ebrahimirad** [spatie/laravel-backup#538] opened 2017-10-03 13:49 UTC
Hi,
I have this when I execute backup:run command:

**`Backup failed because ZipArchive::close(): Read error: No such file or directory`**
 
Also, it is notable that size of my laravel folder (except vendor and node_module) is about 14GB, the database size is around 800MB. When the whole size was fewer the backup run successfuly but after growing the data the backup has failed.

Thanks in advance

**Comment by freekmurze** [comment] 2017-10-03 21:55
It’s a long shot but could you try to increase php’s memory limit?

**Comment by ebrahimirad** [comment] 2017-10-10 06:37
My memory limit is 6144M right now, but I am getting the error.

**Comment by freekmurze** [comment] 2017-10-10 22:11
Then I don't know. If you find a solution for this, please post it here to help other users.

**Comment by ladhadha** [comment] 2017-10-13 09:24
@ebrahimirad how many Gigabytes are free in your disk?

**Comment by ebrahimirad** [comment] 2017-10-13 14:01
@ladhadha about 40GB is free on the disk that temporary backup locate

**Comment by AlexVanderbist** [comment] 2017-11-03 11:07
Did you have a look at #138? That might shave off some more unnecessary bytes.

**Comment by ebrahimirad** [comment] 2017-11-03 19:36
@AlexVanderbist I have excluded all vendor and npm files and folders. The project include the laravel codes (such as app, routes, config and etc) and user files (such as user documents and profile pictures).
All folders and files that included in backup are necessary for me.

**Comment by timgavin** [comment] 2017-11-07 19:03
@ebrahimirad Where are you storing it? Could it be that the destination doesn't allow uploads/files after a certain size? Or the destination is full?

**Comment by ebrahimirad** [comment] 2017-11-11 11:41
@timgavin I store the backup file on dropbox, I have enough space on dropbox

**Comment by freekmurze** [comment] 2018-01-07 07:07
Were you able to solve this?

**Comment by tshafer** [comment] 2018-03-09 19:29
I am having this same issue.

> Unable to open /home/forge/contests.washingtonian.com/storage/app/backup-temp/temp/2018-03-09-01-00-01.zip using mode r: fopen(/home/forge/contests.washingtonian.com/storage/app/backup-temp/temp/2018-03-09-01-00-01.zip): failed to open stream: No such file or directory

> An exception occurred while uploading parts to a multipart upload. The following parts had errors:
> - Part 1058: Error executing "UploadPart" on "https://***.s3.amazonaws.com/https---contests.washingtonian.com/2018-03-09-01-00-01.zip?partNumber=1058&uploadId=GQujTwM5xrc9R7VtpwvZsZgGFbMeP9I7.o4ZtiirBHHwTdw5ezLqHBPSGVD0mJG8_DiWClbi_vkl.6Uzl8DhAjE7L4XxvGKmkstmw8c1WwCYnUYdkqYKGEf1W_tTxHph"; AWS HTTP error: cURL error 52: Empty reply from server (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

**Comment by drbyte** [comment] 2018-03-10 00:50
@tshafer wrote:
> I am having this same issue.

I can't see where yours is the same issue. All the messages are different.
Your error points to an AWS problem: `AWS HTTP error: cURL error 52: Empty reply from server`

**Comment by tshafer** [comment] 2018-03-10 01:10
Look at the first issue.

**Comment by drbyte** [comment] 2018-03-10 05:44
Sigh.
Not the same.

But, since you didn't indicate any troubleshooting steps taken, nor their results, go do the basics:
- check your server volume's available disk space for the user running the commands
- check available RAM, in case zipping is failing from that
- check available file-handles in PHP ... your error mentions 1058 file parts. That's not huge, but not small either.
- you didn't mention the health of your backups generally, nor the usual size, nor the thresholds you've configured

Quite certain this is an issue in your server.

**Comment by wolfcola** [comment] 2018-06-05 03:59
Same error but running it as root works compared to running it as a user on my ubuntu server seems to do the trick.

**Comment by freekmurze** [comment] 2018-06-05 07:43
Closing this issue for now. If there are any errors running the backup, take a look at the advice given by @drbyte above. 

If it still fails, open up a new issue with detailed information on how to reproduce the problem or PR a failing test for us to fix.

**Closed by freekmurze** 2018-06-05 07:43 UTC

**Comment by AliRazaLilani** [comment] 2021-01-25 16:10
Resolved : I was uploading it to google drive and there was not enough space on my drive.
