### ISSUE TITLE
Backup creates double set of directory structure in zip-file

### ISSUE THREAD

**Issue by andersespedalen** [spatie/laravel-backup#1143] opened 2020-11-13 07:56 UTC
Having the projec located at /var/www/{myapp}
Running command; `php artisan backup:run --only-files`

The outputted zip file contains the following directory structure:
\var\www\{myapp}\  contains the laravel project without files. Only empty directory structure
var\www\{myapp}\  contains complete laravel structure with files as expected

This happens both if I run it manually or via cron.

![image](https://user-images.githubusercontent.com/28897489/99043133-2cac3880-258e-11eb-820b-e73810d8666a.png)

Environment:
Homestead 10
Laravel 7

config/backup.php:

```
'backup' => [
        'name' => env('APP_NAME', 'laravel-backup'),
        'source' => [
            'files' => [
                'include' => [
                    base_path(),
                ],
                'exclude' => [
                    base_path('vendor'),
                    base_path('node_modules'),
                ],
                'follow_links' => true,
                'ignore_unreadable_directories' => false,
            ],
            'databases' => [
                'mysql',
            ],
        ],
        'database_dump_compressor' => null,
        'destination' => [
            'filename_prefix' => '',
            'disks' => [
                'backup',
            ],
        ],
        'temporary_directory' => storage_path('app/backup-temp'),
    ],
    'notifications' => [
        'notifications' => [
            \Spatie\Backup\Notifications\Notifications\BackupHasFailed::class => ['mail'],
            \Spatie\Backup\Notifications\Notifications\UnhealthyBackupWasFound::class => ['mail'],
            \Spatie\Backup\Notifications\Notifications\CleanupHasFailed::class => ['mail'],
            \Spatie\Backup\Notifications\Notifications\BackupWasSuccessful::class => ['mail'],
            \Spatie\Backup\Notifications\Notifications\HealthyBackupWasFound::class => ['mail'],
            \Spatie\Backup\Notifications\Notifications\CleanupWasSuccessful::class => ['mail'],
        ],
        'notifiable' => \Spatie\Backup\Notifications\Notifiable::class,
        'mail' => [
            'to' => '{ my_email }',
            'from' => [
                'address' => env('MAIL_FROM_ADDRESS', 'hello@example.com'),
                'name' => env('MAIL_FROM_NAME', 'Example'),
            ],
        ],
        'slack' => [
            'webhook_url' => '',
            'channel' => null,
            'username' => null,
            'icon' => null,
        ],
    ],
    'monitor_backups' => [
        [
            'name' => env('APP_NAME', 'laravel-backup'),
            'disks' => ['local'],
            'health_checks' => [
                \Spatie\Backup\Tasks\Monitor\HealthChecks\MaximumAgeInDays::class => 1,
                \Spatie\Backup\Tasks\Monitor\HealthChecks\MaximumStorageInMegabytes::class => 5000,
            ],
        ],
    ],
    'cleanup' => [
        'strategy' => \Spatie\Backup\Tasks\Cleanup\Strategies\DefaultStrategy::class,
        'default_strategy' => [
            'keep_all_backups_for_days' => 7,
            'keep_daily_backups_for_days' => 16,
            'keep_weekly_backups_for_weeks' => 8,
            'keep_monthly_backups_for_months' => 4,
            'keep_yearly_backups_for_years' => 2,
            'delete_oldest_backups_when_using_more_megabytes_than' => 5000,
        ],
    ],
```

config/filesystem.php
```
...
'disks' => [
...
        'backup' => [
            'driver' => 'local',
            'root' => storage_path('app/backup'),
        ],
...
```

**Comment by freekmurze** [comment] 2020-12-14 11:50
I cannot reproduce, moving this to a discussion.

Feel free to submit a test that reproduces this error.

**Closed** 2020-12-14 11:50 UTC
