### ISSUE TITLE
Ignoring the include/exclude settings

### ISSUE THREAD

**Issue by nat-mystudiosessions** [spatie/laravel-backup#555] opened 2017-10-21 20:30 UTC
Thanks for building such an awesome tool!

I installed a fresh copy of laravel-backup in my Windows local environment. I'm having a weird issue where after the `backup:run` command is complete the new zip file contains a file structure that starts from the root drive, then to the laragon folder (I'm on Windows). Inside the laragon folder is everything that is on my desktop laragon folder, including all my projects in the www folder (not just the current project where I ran the backup command). It also has each project's .git, node_modules, and vendor directories, so you can imagine how large this zip file is (about 350 Mb).

```
php artisan backup:run
Starting backup...
Dumping database website...
Determining files to backup...
Zipping 24256 files...
Created zip containing 24256 files. Size is 349.97 MB
Copying zip to disk named local...
Successfully copied zip to disk named local.
Backup completed!
```

I put a temporary `dd(base_path());` at the top of the config/backup.php file, ran the `backup:run` command again and the screen printed the proper expected project base path directory

```
php artisan backup:run
"C:\laragon\www\project"
```

I'm not sure what else could be the issue. Is it perhaps this package isn't for Windows local environments?

I'd appreciate any help with this. Thanks in advance!

**Comment by andrei930** [comment] 2017-10-30 15:32
Having the same problem on an Ubuntu provisioned servers. 

I've noticed that this started to happen after updating the projects to Laravel 5.5.

Using spatie/laravel-backup 5.0.5.

Here's a snippet of the laravel-backup.php config file excluding all the files:
`
                /*
                 * The list of directories and files that will be included in the backup.
                 */
                'include' => [
                    //
                ],

                /*
                 * These directories and files will be excluded from the backup.
                 *
                 * Directories used by the backup process will automatically be excluded.
                 */
                'exclude' => [
                    base_path(),
                    base_path('vendor'),
                    base_path('node_modules'),
                ],
`

**Comment by andrei930** [comment] 2017-11-02 15:22
Nevermind, in my case this was caused by the fact that I've recently updated Laravel and other packeges. 

I've noticed that spatie/laravel-backup has changed the vendor published config from laravel-backup.php to backup.php. Everything works fine once you rename your old config file.

**Closed** 2017-11-02 15:43 UTC

**Comment by nat-mystudiosessions** [comment] 2017-11-06 00:20
Thanks @andrei930, I'm actually not using vendor published file. The problem remains on my side. @freekmurze any ideas where I need to look?
