### ISSUE TITLE
Target [Spatie\Backup\Tasks\Cleanup\CleanupStrategy] is not instantiable while building

### ISSUE THREAD

**Issue by JunaidKhan046** [spatie/laravel-backup#1058] opened 2020-04-17 00:05 UTC
Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   Illuminate\Contracts\Container\BindingResolutionException  : Target [Spatie\Backup\Tasks\Cleanup\CleanupStrategy] is not instantiable while building [Spatie\Backup\Commands\CleanupCommand].

  at /var/www/homizone/vendor/laravel/framework/src/Illuminate/Container/Container.php:979
    975|         } else {
    976|             $message = "Target [$concrete] is not instantiable.";
    977|         }
    978| 
  > 979|         throw new BindingResolutionException($message);
    980|     }
    981| 
    982|     /**
    983|      * Throw an exception for an unresolvable primitive.

  Exception trace:

  1   Illuminate\Container\Container::notInstantiable("Spatie\Backup\Tasks\Cleanup\CleanupStrategy")
      /var/www/homizone/vendor/laravel/framework/src/Illuminate/Container/Container.php:813

  2   Illuminate\Container\Container::build("Spatie\Backup\Tasks\Cleanup\CleanupStrategy")
      /var/www/homizone/vendor/laravel/framework/src/Illuminate/Container/Container.php:262

  Please use the argument -v to see more details.
I facing this issue please help me

i am using this composer require spatie/laravel-backup

in 
Laravel framework : 6.0
PHP version: 7.2.29-1+ubuntu18.04.1+deb.sury.org+1 
Server Nginx : 1.4
OS : Linux Ubuntu 18.04

**Comment by j5k** [comment] 2020-04-17 11:53
Duplicate of #1051

**Closed** 2020-04-17 11:54 UTC

**Comment by JunaidKhan046** [comment] 2020-04-18 09:53
I am trying #1051 but composer show the same error.

**Comment by erlangp** [comment] 2020-07-09 16:21
> remove the `config.php` file located in `bootstrap/cache/`

https://github.com/spatie/laravel-backup/issues/957#issuecomment-569092998

**Comment by talha2k** [comment] 2024-02-13 13:01
https://github.com/spatie/laravel-backup/issues/957#issuecomment-538835302
