### ISSUE TITLE
Misuse of shell builtins.

### ISSUE THREAD

**Issue by yadounis** [spatie/laravel-backup#93] opened 2016-03-16 12:28 UTC
Hi,
I got this problem when running backup:run

`Starting backup...`
`Dumping database prostats_db...`
`Backup failed because The dump process failed with exitcode 2 : Misuse of shell builtins.`
`Backup completed!`

I'm running on L5.2, PHP5.6 and Debian 8

**Comment by freekmurze** [comment] 2016-03-16 12:58
Duplicate of #92

**Closed by freekmurze** 2016-03-16 12:58 UTC
