### ISSUE TITLE
Problem with clean in google drive

### ISSUE THREAD

**Issue by jpussacq** [spatie/laravel-backup#633] opened 2018-02-21 11:40 UTC
Hi. I am using laravel-backup with very good results. The only problem is that it does not clean in Google Drive and the disk is full. I always receive this message:

> Backup name: 1ibtk0QiroA4yErNjZqncaYQ3oxx5YETl
> Disk: google
> Newest backup size: No backups were made yet
> Total storage used: 0 KB
> Newest backup date: No backups were made yet
> Oldest backup date: No backups were made yet

**Comment by Braunson** [comment] 2018-02-28 19:36
Same issue in #612

**Comment by freekmurze** [comment] 2018-02-28 19:39
Closing as it is a duplicate of #612

**Closed by freekmurze** 2018-02-28 19:39 UTC
