### ISSUE TITLE
I cant connect to database

### ISSUE THREAD

**Issue by murilolivorato** [spatie/laravel-backup#1373] opened 2021-08-16 18:30 UTC
Hello , I am trying to use  laravel-backup .
But when I run the command - php artisan backup:run . it gives me this error - 

```
Backup failed because The dump process failed with exitcode 127 : Command not found : sh: 1: mysqldump: not found
.
#0 /var/www/db_one/vendor/spatie/db-dumper/src/DbDumper.php(263): Spatie\DbDumper\Exceptions\DumpFailed::processDidNotEndSuccessfully(Object(Symfony\Component\Process\Process))
#1 /var/www/db_one/vendor/spatie/db-dumper/src/Databases/MySql.php(203): Spatie\DbDumper\DbDumper->checkIfDumpWasSuccessFul(Object(Symfony\Component\Process\Process), '/var/www/leiloe...')
#2 /var/www/db_one/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(260): Spatie\DbDumper\Databases\MySql->dumpToFile('/var/www/leiloe...')
#3 [internal function]: Spatie\Backup\Tasks\Backup\BackupJob->Spatie\Backup\Tasks\Backup\{closure}(Object(Spatie\DbDumper\Databases\MySql), 'mysql')
#4 /var/www/db_one/vendor/laravel/framework/src/Illuminate/Support/Collection.php(638): array_map(Object(Closure), Array, Array)
#5 /var/www/db_one/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(263): Illuminate\Support\Collection->map(Object(Closure))
#6 /var/www/db_one/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(171): Spatie\Backup\Tasks\Backup\BackupJob->dumpDatabases()
#7 /var/www/db_one/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(147): Spatie\Backup\Tasks\Backup\BackupJob->createBackupManifest()
#8 /var/www/db_one/vendor/spatie/laravel-backup/src/Commands/BackupCommand.php(56): Spatie\Backup\Tasks\Backup\BackupJob->run()
#9 [internal function]: Spatie\Backup\Commands\BackupCommand->handle()
#10 /var/www/db_one/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): call_user_func_array(Array, Array)
#11 /var/www/db_one/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#12 /var/www/db_one/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(95): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#13 /var/www/db_one/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(39): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure
))
#14 /var/www/db_one/vendor/laravel/framework/src/Illuminate/Container/Container.php(596): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#15 /var/www/db_one/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\Container\Container->call(Array)
#16 /var/www/db_one/vendor/symfony/console/Command/Command.php(258): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#17 /var/www/db_one/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Con
sole\OutputStyle))
#18 /var/www/db_one/vendor/spatie/laravel-backup/src/Commands/BaseCommand.php(16): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output
\ConsoleOutput))
#19 /var/www/db_one/vendor/symfony/console/Application.php(920): Spatie\Backup\Commands\BaseCommand->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOu
tput))
#20 /var/www/db_one/vendor/symfony/console/Application.php(266): Symfony\Component\Console\Application->doRunCommand(Object(Spatie\Backup\Commands\BackupCommand), Object(Symfony\Component\Console\Input\Arg
vInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /var/www/db_one/vendor/symfony/console/Application.php(142): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\Cons
oleOutput))
#22 /var/www/db_one/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Compone
nt\Console\Output\ConsoleOutput))
#23 /var/www/db_one/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Compone
nt\Console\Output\ConsoleOutput))
#24 /var/www/db_one/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 {main}
Sending notification failed
Backup failed because: The dump process failed with exitcode 127 : Command not found : sh: 1: mysqldump: not found
.

```

I am using in a Laravel project that uses  - 7.28.4 Laravel .

this is my config - 
config/backup -

```
 'backup' => [
....
 'source' => [
     'databases' => [
                'mysql',
            ],
        ],
```
.env file 
```
DB_CONNECTION=mysql
DB_HOST=mysql
DB_PORT=3306
DB_DATABASE=db_one
DB_USERNAME=root
DB_PASSWORD=root

```

composer.json
```
 "require": {
        "php": "^7.2.5",
         ....
        "spatie/laravel-backup": "^6.16"
    },
```

**Comment by erikn69** [comment] 2021-08-16 21:08
Duplicate of #891 

[dumping-the-database](https://spatie.be/docs/laravel-backup/v7/installation-and-setup#dumping-the-database)
>This is caused by mysqldump not being found. Either move the mysqldump to location in mentioned in the error or add the current path the dump_binary_path in the database config (https://docs.spatie.be/laravel-backup/v6/installation-and-setup#dumping-the-database)

>Just in case anyone comes looking for this, find WORKSPACE_INSTALL_MYSQL_CLIENT and update it to true and rebuild workspace container.
`WORKSPACE_INSTALL_MYSQL_CLIENT=true`

**Closed** 2021-08-16 21:18 UTC
