### ISSUE TITLE
excludeTables documentation wrong?

### ISSUE THREAD

**Issue by futzlarson** [spatie/laravel-backup#1563] opened 2022-08-11 02:12 UTC
Per `config/backup.php`:

```
             * The content of the database dump may be customized for each connection
             * by adding a 'dump' key to the connection settings in config/database.php.
             * E.g.
             * 'mysql' => [
             *       ...
             *      'dump' => [
             *           'excludeTables' => [
             *                'table_to_exclude_from_backup',
             *                'another_table_to_exclude'
             *            ]
             *       ],
             * ],
```
I have this:

```
            'databases' => [
                'mysql' => [
                    'dump' => [
                        'excludeTables' => [ 'sessions' ]
                    ]
                ]
            ],
```

But get this upon running:

`Argument 1 passed to Spatie\Backup\Tasks\Backup\BackupJobFactory::Spatie\Backup\Tasks\Backup\{closure}() must be of the type string, array given, called in /var/www/production/html/vendor/laravel/framework/src/Illuminate/Collections/Collection.php on line 742`

Not sure what is off there?

**Comment by futzlarson** [comment] 2022-08-11 02:43
I had a feeling I read something wrong and just noticed it's `config/database.php`, _not_ `config/backup.php`. I didn't expect it to be in a separate file. Why not keep it all contained within the backup config?

**Comment by PaolaRuby** [comment] 2022-08-11 21:06
This is not a bug

**Comment by futzlarson** [comment] 2022-08-11 21:07
I know, but isn't it strange that all the backup settings are in `config/backup.php`, except for this one thing, which is in `config/database.php`?

**Comment by PaolaRuby** [comment] 2022-08-11 21:08
Because it the best, not need to know why

**Comment by PaolaRuby** [comment] 2022-08-11 21:13
@futzlarson it uses another laravel package for mysql dump, that package uses default laravel database configs, there is no way to send third party configs to that package

Close this

**Closed** 2022-08-12 00:00 UTC
