### ISSUE TITLE
FTP Adapter Not Found

### ISSUE THREAD

**Issue by temwa** [spatie/laravel-backup#1692] opened 2023-08-08 05:17 UTC
Hi,

When I run the clean or backup artisan commands I get he error below. Please assist.

```
forge@webmobyle2:~/go.webmobyle.com$ php artisan backup:clean
Starting cleanup...

In FilesystemManager.php line 202:

Class "League\Flysystem\Ftp\FtpAdapter" not found
```

**Comment by freekmurze** [comment] 2023-08-08 06:23
Duplicate of # 1691

**Closed** 2023-08-08 06:23 UTC
