### ISSUE TITLE
Backup wont upload to s3

### ISSUE THREAD

**Issue by gergo2007** [spatie/laravel-backup#475] opened 2017-07-05 08:04 UTC
Hi

I get an error message after a while that: Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.

My backup is 220 MBs.

Thank you

**Comment by freekmurze** [comment] 2017-07-05 08:05
Could you check if you're having the same problem on another system? Good change is probably related to something with the server you're trying it on now.

**Comment by inlinkz** [comment] 2017-07-05 11:45
First of all thank you for the awesomely easy lib!

I am having the same problem and I can confirm it happens from different systems. 

It started happening 2 days ago with a 50MB backup. 

While it runs wonderfully up to the creation of the zip (and the local save), when the disk is s3, 
it produces the following:

`Copying zip failed because: An exception occurred while uploading parts to a multipart upload. The following parts had errors:
- Part 1: Error executing "UploadPart" on "https://example.s3.amazonaws.com/https---example.com/2017-07-05-10-47-51.zip?partNumber=1&uploadId=AOHXHJK9bhs76VjhegSo9Q3HiUsTxeW9EXWcNktu5uyQ7x1RWgLtNFA049IUimeb9Z4uQiqwdd336TLRN7t2vw--"; AWS HTTP error: Client error: `PUT https://example.s3.amazonaws.com/https---example.com/2017-07-05-10-47-51.zip?partNumber=1&uploadId=AOHXHJK9bhs76VjhegSo9Q3HiUsTxeW9EXWcNktu5uyQ7x1RWgLtNFA049IUimeb9Z4uQiqwdd336TLRN7t2vw--` resulted in a `400 Bad Request` response:
<?xml version="1.0" encoding="UTF-8"?>
<Code>RequestTimeout</Code><Message>Your socket connection to the server w (truncated...)
 RequestTimeout (client): Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed. - <?xml version="1.0" encoding="UTF-8"?>
<Code>RequestTimeout</Code><Message>Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.</Message><RequestId>43D7743701C57F31</RequestId><HostId>zLkhMnCpku5DTidKgWuzD7Zcy+673l3RDg8mpDV6gSQzQCLV2Hrv4Ht5AkiIBcqnGi4/scsSvCA=</HostId>`

This happens on the writeStream command on BackupDestination file. 

Everything else I use through the S3 library, works/uploads normally. 

Let me know if I can provide any additional info!

Thanks again!

**Comment by gergo2007** [comment] 2017-07-05 13:12
Same error on another server.

**Comment by freekmurze** [comment] 2017-07-05 13:15
Hi, I just tried this with one of my applications, and it worked perfectly.

If you found the problem / solution, report it back here.

**Comment by aaronhuisinga** [comment] 2017-07-05 14:49
We are all of a sudden experiencing this same issue on our production server as well when trying to run our daily backups. The DB is properly dumped and GZipped. It's properly saving locally, but doesn't properly upload to AWS. We're on Ubuntu 16.04.

**Comment by aaronhuisinga** [comment] 2017-07-05 14:53
@freekmurze It looks like this might have something to do with the latest release of the AWS SDK package for PHP. Upgrading to v3.31.0 causes backups to fail, but when I downgrade back to v3.30.4 they work again.

https://github.com/aws/aws-sdk-php/releases

**Comment by gergo2007** [comment] 2017-07-05 15:07
I can also confirm that with v3.30.4 works fine.

**Comment by freekmurze** [comment] 2017-07-05 16:54
@aaronhuisinga I think it's best to open up an issue at their repo.

**Comment by thepenguin1** [comment] 2017-07-08 00:19
I can also confirm this to be an issue. What's the best way to downgrade to a working version (I'm using Laravel Forge).

**Comment by graphem** [comment] 2017-07-10 04:34
Yes same here. Seems to be issue with AWS update, running 3.31.1

**Comment by graphem** [comment] 2017-07-12 19:50
This has been fixed in [AWS 3.31.3](https://github.com/aws/aws-sdk-php/releases/tag/3.31.3)

**Comment by freekmurze** [comment] 2017-07-12 20:38
Great, thanks for let me and the other users of this package know.

**Closed by freekmurze** 2017-07-12 20:38 UTC

**Comment by graphem** [comment] 2017-07-12 20:44
Thanks to you to all the amazing packages you put out there, they are priceless!

**Comment by kstich** [comment] 2017-07-12 20:48
Thanks to everyone who raised this issue and brought it to our attention over on the AWS PHP SDK!

**Comment by jsartisan** [comment] 2018-09-19 10:46
experiencing this issue occasionally. any solution for this? My backup is around 4gb.

**Comment by deanzod** [comment] 2024-05-17 09:43
I've been having this same issue where it fails 95% of the time. It might successfully store a 4GB backup on S3 today, then fail to store a 300MB backup on S3 tomorrow with this error. It completes the local backup ok every time. I think the fact it can store a 4GB one but fails on 300MB ones rules out it being a file size issue.

Anyone got any ideas how to solve this or where to look?
