### ISSUE TITLE
SQL-file per table in ZIP

### ISSUE THREAD

**Issue by ZoWeArdeb** [spatie/laravel-backup#1628] opened 2023-01-12 08:29 UTC
### Discussed in https://github.com/spatie/laravel-backup/discussions/1627

<div type='discussions-op-text'>

<sup>Originally posted by **ZoWeArdeb** January 11, 2023</sup>
Hello,
Is their a param to set, if you want to have an SQL-file for each table instead of a general SQL-file for the complete database?
Because if i want to restore a complete database with a single SQL-file it gives me an error: SQLSTATE[08S01]: Communication link failure: 1153 Got a packet bigger than 'max_allowed_packet' bytes. Due security reasons i'm not planning to upgrade these bytes. So it would be better if i can chunck that one big SQL-file into several small ones (per table). 
If anyone can help me, it would be nice.
Thanks in advance.
Kind regards</div>

**Comment by parallels999** [comment] 2023-01-13 14:28
Duplicate of #1627

**Comment by ajuchacko** [comment] 2023-04-10 05:53
Hey,  @ZoWeArdeb,
Unfortunately I don't think you can do that.
Your particular case doesn't align with the purpose of this package.

What I can suggest is make your own version of this package, you can get head start from here [see](https://github.com/spatie/laravel-backup/blob/981cec4792cc3a38098c6a6323d0d6f6d837c9f5/src/Tasks/Backup/BackupJob.php#L245) Otherwise, use this [spatie/db-dumber](https://github.com/spatie/db-dumper#dump-specific-tables) package. 

All the best 👍

**Closed** 2023-08-11 10:05 UTC
