### ISSUE TITLE
How to avoid backups being created on disk/app_name?

### ISSUE THREAD

**Issue by RM6SS62** [spatie/laravel-backup#1451] opened 2022-01-17 20:37 UTC
I defined a disk this way

`        'backups' => [
            'driver' => 'local',
            'root' => storage_path('backups'),
        ],		
`
Now the backup files aren't created under /storage/backups/ as I would like but in /storage/backups/{APP_NAME}
How do I avoid this?

**Comment by freekmurze** [comment] 2022-01-17 23:35
Duplicate of the discussion.

**Closed by freekmurze** 2022-01-17 23:35 UTC
