### ISSUE TITLE
if cleanup don't do anything,how can I stop send notification?

### ISSUE THREAD

**Issue by lengjunbin-trec** [spatie/laravel-backup#1458] opened 2022-01-20 07:36 UTC
### Discussed in https://github.com/spatie/laravel-backup/discussions/1457

<div type='discussions-op-text'>

<sup>Originally posted by **lengjunbin-trec** January 20, 2022</sup>
I execute `php artisan backup:clean` to clean old backup zip file,if there is not old backup file,I don't want to send notification,only while delete something ,send nontofication</div>

**Comment by freekmurze** [comment] 2022-01-21 09:11
Duplicate of discussion.

**Closed by freekmurze** 2022-01-21 09:11 UTC
