### ISSUE TITLE
I receive two email notifications whenever a backup fails

### ISSUE THREAD

**Issue by trevorgehman** [spatie/laravel-backup#1662] opened 2023-04-26 23:39 UTC
I have an odd, longstanding problem that I simply cannot figure out. Whenever a backup fails, it will always send two identical email notifications at the exact same time:

![CleanShot 2023-04-26 at 18 29 15@2x](https://user-images.githubusercontent.com/3209864/234723933-bb2d4223-48c9-4814-90e2-0c47a793404a.png)

It doesn't matter if the error is due to a timeout, or a S3 issue, I will always get two emails in the event of a failure.

My configuration is set up with a single email:

![CleanShot 2023-04-26 at 18 34 32@2x](https://user-images.githubusercontent.com/3209864/234724534-5ac74252-3d68-41bf-ab01-e6a8cb17a7b1.png)

And the backup is configured to run once, but it does have 'runInBackground()' specified:

<img width="482" alt="CleanShot 2023-04-26 at 18 35 43@2x" src="https://user-images.githubusercontent.com/3209864/234724643-b4c5b4d9-d2c5-4f68-8e17-b8c9c208496d.png">

I'm on version 8.1.7, and PHP 8.2 and MySQL 8.0.32.

The _only_ thing I can think of is that somehow the `backup:run` job is running twice and is actually the _cause_ of the failures, explaining multiple emails. But not sure how that could be happening.

**Comment by trevorgehman** [comment] 2023-04-27 01:04
I can see locally in Telescope that if I set the timeout to 1 second, it fails and there are multiple "BackupHasFailed" events being thrown, which I believe is why multiple notifications are sent:

<img width="1239" alt="CleanShot 2023-04-26 at 20 03 37@2x" src="https://user-images.githubusercontent.com/3209864/234733764-739215d6-f74d-4e2d-bf43-1700652243f7.png">

**Comment by parallels999** [comment] 2023-04-27 19:27
Duplicate of #1553??

**Comment by trevorgehman** [comment] 2023-04-28 01:41
> Duplicate of #1553??

Yes looks like that is the same issue. This seems to be a legitimate bug, as I'm not sure why it's necessary to fire that event more than once, especially since notifications are sent as a result.

**Comment by PaolaRuby** [comment] 2023-04-28 13:42
> I'm not sure why it's necessary to fire that event more than once

It's not that "it's necessary", it's a logic mistake that went unnoticed

https://github.com/spatie/laravel-backup/issues/1553#issuecomment-1203973313

Feel free to make a PR to fix that

**Closed** 2023-08-30 14:16 UTC
Labels: bug
